name: Run Node.js Tests

on:
  push:
    branches:
      - regression-test_anitha
    paths:
      - 'Node.js/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: Node.js
        run: |
          npm install
          npm install --global mocha

      - name: Run Node.js tests
        working-directory: Node.js
        run: mocha
