name: Run Node.js Tests

on:
  push:
    branches:
      - regression-test_anitha
    paths:
      - 'Node.js/**'

jobs:
  test-with-podman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Pull IBM MQ image
        run: podman pull icr.io/ibm-messaging/mq:latest

      - name: Run IBM MQ container (QM1)
        run: |
          podman run \
            --env LICENSE=accept \
            --env MQ_QMGR_NAME=QM1 \
            --env MQ_APP_USER=app \
            --env MQ_APP_PASSWORD=passw0rd \
            --env MQ_ADMIN_USER=admin \
            --env MQ_ADMIN_PASSWORD=passw0rd \
            --volume qm1data:/mnt/mqm \
            --publish 1414:1414 \
            --publish 9443:9443 \
            --detach \
            --name QM1 \
            icr.io/ibm-messaging/mq:latest

      - name: Wait for QMGR to be running
        run: |
          for i in {1..12}; do
            STATUS=$(podman exec QM1 bash -c "dspmq -o json" | jq -r '.[0].state')
            echo "QMGR state: $STATUS"
            if [ "$STATUS" = "Running" ]; then
              echo "QM1 is running"
              break
            fi
            echo "Waiting for QMGR to start..."
            sleep 5
          done

      - name: Install dependencies
        working-directory: Node.js
        run: |
          npm install
          npm install --global mocha

      - name: Run Node.js tests
        working-directory: Node.js
        run: mocha
