name: Run Node tests using git actions secrets

on:
  pull_request:
    branches:
      - master
    paths:
      - 'Node.js/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create env.json from secrets
        working-directory: Node.js
        run: |
          cat << EOF > env.json
          {
            "MQ_ENDPOINTS": [{
              "HOST": "${{ secrets.HOST }}",
              "PORT": "${{ secrets.PORT }}",
              "CHANNEL": "CLOUD.APP.SVRCONN",
              "QMGR": "QMHE",
              "APP_USER": "${{ secrets.APP_USER }}",
              "APP_PASSWORD": "${{ secrets.APP_PASSWORD }}",
              "QUEUE_NAME": "DEV.QUEUE.1",
              "BACKOUT_QUEUE": "DEV.QUEUE.2",
              "MODEL_QUEUE_NAME": "CLOUD.APP.MODEL.QUEUE",
              "DYNAMIC_QUEUE_PREFIX": "APP.REPLIES.*",
              "TOPIC_NAME": "dev/",
              "CIPHER": "TLS_AES_256_GCM_SHA384",
              "CIPHER_SUITE": "TLS_AES_256_GCM_SHA384",
              "KEY_REPOSITORY": "./keys/clientkey"
            }]
          }
          EOF

          echo "env.json path: $(pwd)/env.json"
          cat env.json

      - name: Install dependencies
        working-directory: Node.js
        run: |
          npm install
          npm install --global mocha

      - name: Run Node.js tests
        working-directory: Node.js
        env: 
          EnvFile: "/home/runner/work/mq-dev-patterns/mq-dev-patterns/Node.js/env.json"
        run: mocha
        